/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Certificate_validation.h
 *
 * Validation status (only while &#x60;pending&#x60;). 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Certificate_validation_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Certificate_validation_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



/// <summary>
/// Validation status (only while &#x60;pending&#x60;). 
/// </summary>
class  Certificate_validation
    : public ModelBase
{
public:
    Certificate_validation();
    virtual ~Certificate_validation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Certificate_validation members

    /// <summary>
    /// Number of validation attempts made. 
    /// </summary>
    int32_t getAttempt() const;
    bool attemptIsSet() const;
    void unsetAttempt();

    void setAttempt(int32_t value);

    /// <summary>
    /// Date and time of the next validation attempt in ISO8601. 
    /// </summary>
    utility::datetime getNext() const;
    bool nextIsSet() const;
    void unsetNext();

    void setNext(const utility::datetime& value);


protected:
    int32_t m_Attempt;
    bool m_AttemptIsSet;
    utility::datetime m_Next;
    bool m_NextIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Certificate_validation_H_ */
