/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Create_instance_request_env.h
 *
 * Key/value pairs to be set as environment variables at boot time. Values must be strings. 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Create_instance_request_env_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Create_instance_request_env_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



/// <summary>
/// Key/value pairs to be set as environment variables at boot time. Values must be strings. 
/// </summary>
class  Create_instance_request_env
    : public ModelBase
{
public:
    Create_instance_request_env();
    virtual ~Create_instance_request_env();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Create_instance_request_env members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();

    void setAdditionalProperties(const utility::string_t& value);


protected:
    utility::string_t m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Create_instance_request_env_H_ */
