/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_certificates_default_response_errors_inner.h
 *
 * 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Get_certificates_default_response_errors_inner_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Get_certificates_default_response_errors_inner_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"


namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



/// <summary>
/// 
/// </summary>
class  Get_certificates_default_response_errors_inner
    : public ModelBase
{
public:
    Get_certificates_default_response_errors_inner();
    virtual ~Get_certificates_default_response_errors_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Get_certificates_default_response_errors_inner members

    /// <summary>
    /// HTTP status code 
    /// </summary>
    int32_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(int32_t value);


protected:
    int32_t m_Status;
    bool m_StatusIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Get_certificates_default_response_errors_inner_H_ */
