/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data.h
 *
 * 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"

#include "UnikraftCloudV1APIClient/model/Autoscale_policy.h"
#include <vector>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {

class Autoscale_policy;


/// <summary>
/// 
/// </summary>
class  Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data
    : public ModelBase
{
public:
    Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data();
    virtual ~Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Autoscale_policy>>& getPolicies();
    bool policiesIsSet() const;
    void unsetPolicies();

    void setPolicies(const std::vector<std::shared_ptr<Autoscale_policy>>& value);


protected:
    std::vector<std::shared_ptr<Autoscale_policy>> m_Policies;
    bool m_PoliciesIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data_H_ */
