/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_instance_logs_200_response_data_instances_inner_available.h
 *
 * Description of the log availability. 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Get_instance_logs_200_response_data_instances_inner_available_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Get_instance_logs_200_response_data_instances_inner_available_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"


namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



/// <summary>
/// Description of the log availability. 
/// </summary>
class  Get_instance_logs_200_response_data_instances_inner_available
    : public ModelBase
{
public:
    Get_instance_logs_200_response_data_instances_inner_available();
    virtual ~Get_instance_logs_200_response_data_instances_inner_available();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Get_instance_logs_200_response_data_instances_inner_available members

    /// <summary>
    /// The first byte offset that can be retrieved. 
    /// </summary>
    int64_t getStart() const;
    bool startIsSet() const;
    void unsetStart();

    void setStart(int64_t value);

    /// <summary>
    /// The last byte offset that can be retrieved. 
    /// </summary>
    int64_t getEnd() const;
    bool endIsSet() const;
    void unsetEnd();

    void setEnd(int64_t value);


protected:
    int64_t m_Start;
    bool m_StartIsSet;
    int64_t m_End;
    bool m_EndIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Get_instance_logs_200_response_data_instances_inner_available_H_ */
