/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Instance_service_group_domains_inner_certificate.h
 *
 * TLS certificate to use for the domain.  Note: Only allowed for FQDNs, not for subdomains. Subdomains like &#x60;my-project&#x60; inherit the wildcard &#x60;*.&lt;metro&gt;.kraft.host&#x60; certificate. If you specify an FQDN like &#x60;www.example.com&#x60;, Unikraft Cloud will automatically pick the certificate with the matching CN or trigger a certificate request (see [here](https://unikraft.cloud/docs/api/v1/certificates)). 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Instance_service_group_domains_inner_certificate_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Instance_service_group_domains_inner_certificate_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



/// <summary>
/// TLS certificate to use for the domain.  Note: Only allowed for FQDNs, not for subdomains. Subdomains like &#x60;my-project&#x60; inherit the wildcard &#x60;*.&lt;metro&gt;.kraft.host&#x60; certificate. If you specify an FQDN like &#x60;www.example.com&#x60;, Unikraft Cloud will automatically pick the certificate with the matching CN or trigger a certificate request (see [here](https://unikraft.cloud/docs/api/v1/certificates)). 
/// </summary>
class  Instance_service_group_domains_inner_certificate
    : public ModelBase
{
public:
    Instance_service_group_domains_inner_certificate();
    virtual ~Instance_service_group_domains_inner_certificate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Instance_service_group_domains_inner_certificate members

    /// <summary>
    /// UUID of the certificate
    /// </summary>
    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();

    void setUuid(const utility::string_t& value);

    /// <summary>
    /// Name of the certificate
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);


protected:
    utility::string_t m_Uuid;
    bool m_UuidIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Instance_service_group_domains_inner_certificate_H_ */
