/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Instance_service_group.h
 *
 * Description of the service that the instance is part of.  Note: Only if attached to a service. 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Instance_service_group_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Instance_service_group_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"

#include "UnikraftCloudV1APIClient/model/Instance_service_group_domains_inner.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {

class Instance_service_group_domains_inner;


/// <summary>
/// Description of the service that the instance is part of.  Note: Only if attached to a service. 
/// </summary>
class  Instance_service_group
    : public ModelBase
{
public:
    Instance_service_group();
    virtual ~Instance_service_group();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Instance_service_group members

    /// <summary>
    /// The name of an existing service.  Note: You need to specify either an existing [service](https://unikraft.cloud/docs/api/v1/services) via &#x60;uuid&#x60; or &#x60;name&#x60;, or provide a description of a new service. If a description for a new service is provided, the service is created and the instance attached. The service will receive an auto-generated name. Specifying an empty &#x60;service_group&#x60; object creates a new service with no services published. 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// UUID of an existing service. 
    /// </summary>
    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();

    void setUuid(const utility::string_t& value);

    /// <summary>
    /// Description of domains to associate with the service.  Default: auto-generated Note: If &#x60;name&#x60; is specified without also providing a domain, a domain is derived from &#x60;name&#x60; by appending an 8 characters long random alphanumeric suffix and the metro&#39;s domain name. For example, setting the name to &#x60;my-project&#x60; without also providing a domain results in an auto-generated domain of &#x60;my-project-&lt;random&gt;.fra0.kraft.host&#x60;. 
    /// </summary>
    std::vector<std::shared_ptr<Instance_service_group_domains_inner>>& getDomains();
    bool domainsIsSet() const;
    void unsetDomains();

    void setDomains(const std::vector<std::shared_ptr<Instance_service_group_domains_inner>>& value);


protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Uuid;
    bool m_UuidIsSet;
    std::vector<std::shared_ptr<Instance_service_group_domains_inner>> m_Domains;
    bool m_DomainsIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Instance_service_group_H_ */
