/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Start_instances_200_response_data.h
 *
 * 
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_Start_instances_200_response_data_H_
#define CLOUD_UNIKRAFT_V1_MODEL_Start_instances_200_response_data_H_


#include "UnikraftCloudV1APIClient/ModelBase.h"

#include <vector>
#include "UnikraftCloudV1APIClient/model/Start_instances_200_response_data_instances_inner.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {

class Start_instances_200_response_data_instances_inner;


/// <summary>
/// 
/// </summary>
class  Start_instances_200_response_data
    : public ModelBase
{
public:
    Start_instances_200_response_data();
    virtual ~Start_instances_200_response_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Start_instances_200_response_data members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Start_instances_200_response_data_instances_inner>>& getInstances();
    bool instancesIsSet() const;
    void unsetInstances();

    void setInstances(const std::vector<std::shared_ptr<Start_instances_200_response_data_instances_inner>>& value);


protected:
    std::vector<std::shared_ptr<Start_instances_200_response_data_instances_inner>> m_Instances;
    bool m_InstancesIsSet;
};


}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_Start_instances_200_response_data_H_ */
