/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IHttpBody.h
 *
 * This is the interface for contents that can be sent to a remote HTTP server.
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_IHttpBody_H_
#define CLOUD_UNIKRAFT_V1_MODEL_IHttpBody_H_


#include <iostream>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {

class  IHttpBody
{
public:
    virtual ~IHttpBody() { }

    virtual void writeTo( std::ostream& stream ) = 0;
};

}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_IHttpBody_H_ */
