/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * JsonBody.h
 *
 * This is a JSON http body which can be submitted via http
 */

#ifndef CLOUD_UNIKRAFT_V1_MODEL_JsonBody_H_
#define CLOUD_UNIKRAFT_V1_MODEL_JsonBody_H_


#include "UnikraftCloudV1APIClient/IHttpBody.h"

#include <cpprest/json.h>

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {

class  JsonBody
    : public IHttpBody
{
public:
    JsonBody( const web::json::value& value );
    virtual ~JsonBody();

    void writeTo( std::ostream& target ) override;

protected:
    web::json::value m_Json;
};

}
}
}
}

#endif /* CLOUD_UNIKRAFT_V1_MODEL_JsonBody_H_ */
