/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Create_services_request_services_inner.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Create_services_request_services_inner::Create_services_request_services_inner()
{
    m_Port = 0;
    m_PortIsSet = false;
    m_Destination_port = 0;
    m_Destination_portIsSet = false;
    m_HandlersIsSet = false;
    m_DomainsIsSet = false;
}

Create_services_request_services_inner::~Create_services_request_services_inner()
{
}

void Create_services_request_services_inner::validate()
{
    // TODO: implement validation
}

web::json::value Create_services_request_services_inner::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_PortIsSet)
    {
        val[utility::conversions::to_string_t(U("port"))] = ModelBase::toJson(m_Port);
    }
    if(m_Destination_portIsSet)
    {
        val[utility::conversions::to_string_t(U("destination_port"))] = ModelBase::toJson(m_Destination_port);
    }
    if(m_HandlersIsSet)
    {
        val[utility::conversions::to_string_t(U("handlers"))] = ModelBase::toJson(m_Handlers);
    }
    if(m_DomainsIsSet)
    {
        val[utility::conversions::to_string_t(U("domains"))] = ModelBase::toJson(m_Domains);
    }

    return val;
}

bool Create_services_request_services_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("port"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("port")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPort;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPort);
            setPort(refVal_setPort);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("destination_port"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("destination_port")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDestinationPort;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDestinationPort);
            setDestinationPort(refVal_setDestinationPort);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("handlers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("handlers")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Service_mapping>> refVal_setHandlers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHandlers);
            setHandlers(refVal_setHandlers);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("domains"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("domains")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Create_services_request_services_inner_domains_inner>> refVal_setDomains;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDomains);
            setDomains(refVal_setDomains);
        }
    }
    return ok;
}

void Create_services_request_services_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_PortIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("port")), m_Port));
    }
    if(m_Destination_portIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("destination_port")), m_Destination_port));
    }
    if(m_HandlersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("handlers")), m_Handlers));
    }
    if(m_DomainsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("domains")), m_Domains));
    }
}

bool Create_services_request_services_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("port"))))
    {
        int32_t refVal_setPort;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("port"))), refVal_setPort );
        setPort(refVal_setPort);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("destination_port"))))
    {
        int32_t refVal_setDestinationPort;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("destination_port"))), refVal_setDestinationPort );
        setDestinationPort(refVal_setDestinationPort);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("handlers"))))
    {
        std::vector<std::shared_ptr<Service_mapping>> refVal_setHandlers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("handlers"))), refVal_setHandlers );
        setHandlers(refVal_setHandlers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("domains"))))
    {
        std::vector<std::shared_ptr<Create_services_request_services_inner_domains_inner>> refVal_setDomains;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("domains"))), refVal_setDomains );
        setDomains(refVal_setDomains);
    }
    return ok;
}

int32_t Create_services_request_services_inner::getPort() const
{
    return m_Port;
}

void Create_services_request_services_inner::setPort(int32_t value)
{
    m_Port = value;
    m_PortIsSet = true;
}

bool Create_services_request_services_inner::portIsSet() const
{
    return m_PortIsSet;
}

void Create_services_request_services_inner::unsetPort()
{
    m_PortIsSet = false;
}
int32_t Create_services_request_services_inner::getDestinationPort() const
{
    return m_Destination_port;
}

void Create_services_request_services_inner::setDestinationPort(int32_t value)
{
    m_Destination_port = value;
    m_Destination_portIsSet = true;
}

bool Create_services_request_services_inner::destinationPortIsSet() const
{
    return m_Destination_portIsSet;
}

void Create_services_request_services_inner::unsetDestination_port()
{
    m_Destination_portIsSet = false;
}
std::vector<std::shared_ptr<Service_mapping>>& Create_services_request_services_inner::getHandlers()
{
    return m_Handlers;
}

void Create_services_request_services_inner::setHandlers(const std::vector<std::shared_ptr<Service_mapping>>& value)
{
    m_Handlers = value;
    m_HandlersIsSet = true;
}

bool Create_services_request_services_inner::handlersIsSet() const
{
    return m_HandlersIsSet;
}

void Create_services_request_services_inner::unsetHandlers()
{
    m_HandlersIsSet = false;
}
std::vector<std::shared_ptr<Create_services_request_services_inner_domains_inner>>& Create_services_request_services_inner::getDomains()
{
    return m_Domains;
}

void Create_services_request_services_inner::setDomains(const std::vector<std::shared_ptr<Create_services_request_services_inner_domains_inner>>& value)
{
    m_Domains = value;
    m_DomainsIsSet = true;
}

bool Create_services_request_services_inner::domainsIsSet() const
{
    return m_DomainsIsSet;
}

void Create_services_request_services_inner::unsetDomains()
{
    m_DomainsIsSet = false;
}
}
}
}
}


