/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Create_services_request.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Create_services_request::Create_services_request()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_ServicesIsSet = false;
}

Create_services_request::~Create_services_request()
{
}

void Create_services_request::validate()
{
    // TODO: implement validation
}

web::json::value Create_services_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_ServicesIsSet)
    {
        val[utility::conversions::to_string_t(U("services"))] = ModelBase::toJson(m_Services);
    }

    return val;
}

bool Create_services_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("services"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("services")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Create_services_request_services_inner>> refVal_setServices;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServices);
            setServices(refVal_setServices);
        }
    }
    return ok;
}

void Create_services_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_ServicesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("services")), m_Services));
    }
}

bool Create_services_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("services"))))
    {
        std::vector<std::shared_ptr<Create_services_request_services_inner>> refVal_setServices;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("services"))), refVal_setServices );
        setServices(refVal_setServices);
    }
    return ok;
}

utility::string_t Create_services_request::getName() const
{
    return m_Name;
}

void Create_services_request::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Create_services_request::nameIsSet() const
{
    return m_NameIsSet;
}

void Create_services_request::unsetName()
{
    m_NameIsSet = false;
}
std::vector<std::shared_ptr<Create_services_request_services_inner>>& Create_services_request::getServices()
{
    return m_Services;
}

void Create_services_request::setServices(const std::vector<std::shared_ptr<Create_services_request_services_inner>>& value)
{
    m_Services = value;
    m_ServicesIsSet = true;
}

bool Create_services_request::servicesIsSet() const
{
    return m_ServicesIsSet;
}

void Create_services_request::unsetServices()
{
    m_ServicesIsSet = false;
}
}
}
}
}


