/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Create_volumes_request_inner.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Create_volumes_request_inner::Create_volumes_request_inner()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Size_mb = 0;
    m_Size_mbIsSet = false;
}

Create_volumes_request_inner::~Create_volumes_request_inner()
{
}

void Create_volumes_request_inner::validate()
{
    // TODO: implement validation
}

web::json::value Create_volumes_request_inner::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Size_mbIsSet)
    {
        val[utility::conversions::to_string_t(U("size_mb"))] = ModelBase::toJson(m_Size_mb);
    }

    return val;
}

bool Create_volumes_request_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("size_mb"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("size_mb")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSizeMb;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSizeMb);
            setSizeMb(refVal_setSizeMb);
        }
    }
    return ok;
}

void Create_volumes_request_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_Size_mbIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("size_mb")), m_Size_mb));
    }
}

bool Create_volumes_request_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("size_mb"))))
    {
        int32_t refVal_setSizeMb;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("size_mb"))), refVal_setSizeMb );
        setSizeMb(refVal_setSizeMb);
    }
    return ok;
}

utility::string_t Create_volumes_request_inner::getName() const
{
    return m_Name;
}

void Create_volumes_request_inner::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Create_volumes_request_inner::nameIsSet() const
{
    return m_NameIsSet;
}

void Create_volumes_request_inner::unsetName()
{
    m_NameIsSet = false;
}
int32_t Create_volumes_request_inner::getSizeMb() const
{
    return m_Size_mb;
}

void Create_volumes_request_inner::setSizeMb(int32_t value)
{
    m_Size_mb = value;
    m_Size_mbIsSet = true;
}

bool Create_volumes_request_inner::sizeMbIsSet() const
{
    return m_Size_mbIsSet;
}

void Create_volumes_request_inner::unsetSize_mb()
{
    m_Size_mbIsSet = false;
}
}
}
}
}


