/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Get_certificates_default_response_errors_inner.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Get_certificates_default_response_errors_inner::Get_certificates_default_response_errors_inner()
{
    m_Status = 0;
    m_StatusIsSet = false;
}

Get_certificates_default_response_errors_inner::~Get_certificates_default_response_errors_inner()
{
}

void Get_certificates_default_response_errors_inner::validate()
{
    // TODO: implement validation
}

web::json::value Get_certificates_default_response_errors_inner::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_StatusIsSet)
    {
        val[utility::conversions::to_string_t(U("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool Get_certificates_default_response_errors_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("status")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
        }
    }
    return ok;
}

void Get_certificates_default_response_errors_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("status")), m_Status));
    }
}

bool Get_certificates_default_response_errors_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("status"))))
    {
        int32_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}

int32_t Get_certificates_default_response_errors_inner::getStatus() const
{
    return m_Status;
}

void Get_certificates_default_response_errors_inner::setStatus(int32_t value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool Get_certificates_default_response_errors_inner::statusIsSet() const
{
    return m_StatusIsSet;
}

void Get_certificates_default_response_errors_inner::unsetStatus()
{
    m_StatusIsSet = false;
}
}
}
}
}


