/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Get_volumes_200_response_data.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Get_volumes_200_response_data::Get_volumes_200_response_data()
{
    m_VolumesIsSet = false;
}

Get_volumes_200_response_data::~Get_volumes_200_response_data()
{
}

void Get_volumes_200_response_data::validate()
{
    // TODO: implement validation
}

web::json::value Get_volumes_200_response_data::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_VolumesIsSet)
    {
        val[utility::conversions::to_string_t(U("volumes"))] = ModelBase::toJson(m_Volumes);
    }

    return val;
}

bool Get_volumes_200_response_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("volumes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("volumes")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Volume>> refVal_setVolumes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVolumes);
            setVolumes(refVal_setVolumes);
        }
    }
    return ok;
}

void Get_volumes_200_response_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_VolumesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("volumes")), m_Volumes));
    }
}

bool Get_volumes_200_response_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("volumes"))))
    {
        std::vector<std::shared_ptr<Volume>> refVal_setVolumes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("volumes"))), refVal_setVolumes );
        setVolumes(refVal_setVolumes);
    }
    return ok;
}

std::vector<std::shared_ptr<Volume>>& Get_volumes_200_response_data::getVolumes()
{
    return m_Volumes;
}

void Get_volumes_200_response_data::setVolumes(const std::vector<std::shared_ptr<Volume>>& value)
{
    m_Volumes = value;
    m_VolumesIsSet = true;
}

bool Get_volumes_200_response_data::volumesIsSet() const
{
    return m_VolumesIsSet;
}

void Get_volumes_200_response_data::unsetVolumes()
{
    m_VolumesIsSet = false;
}
}
}
}
}


