/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data()
{
    m_PoliciesIsSet = false;
}

Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::~Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data()
{
}

void Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::validate()
{
    // TODO: implement validation
}

web::json::value Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_PoliciesIsSet)
    {
        val[utility::conversions::to_string_t(U("policies"))] = ModelBase::toJson(m_Policies);
    }

    return val;
}

bool Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("policies"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("policies")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Autoscale_policy>> refVal_setPolicies;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPolicies);
            setPolicies(refVal_setPolicies);
        }
    }
    return ok;
}

void Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_PoliciesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("policies")), m_Policies));
    }
}

bool Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("policies"))))
    {
        std::vector<std::shared_ptr<Autoscale_policy>> refVal_setPolicies;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("policies"))), refVal_setPolicies );
        setPolicies(refVal_setPolicies);
    }
    return ok;
}

std::vector<std::shared_ptr<Autoscale_policy>>& Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::getPolicies()
{
    return m_Policies;
}

void Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::setPolicies(const std::vector<std::shared_ptr<Autoscale_policy>>& value)
{
    m_Policies = value;
    m_PoliciesIsSet = true;
}

bool Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::policiesIsSet() const
{
    return m_PoliciesIsSet;
}

void Get_autoscale_policy_by_service_uuid_and_policy_name_200_response_data::unsetPolicies()
{
    m_PoliciesIsSet = false;
}
}
}
}
}


