/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Instance_service_group.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Instance_service_group::Instance_service_group()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_DomainsIsSet = false;
}

Instance_service_group::~Instance_service_group()
{
}

void Instance_service_group::validate()
{
    // TODO: implement validation
}

web::json::value Instance_service_group::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_DomainsIsSet)
    {
        val[utility::conversions::to_string_t(U("domains"))] = ModelBase::toJson(m_Domains);
    }

    return val;
}

bool Instance_service_group::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("domains"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("domains")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Instance_service_group_domains_inner>> refVal_setDomains;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDomains);
            setDomains(refVal_setDomains);
        }
    }
    return ok;
}

void Instance_service_group::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_DomainsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("domains")), m_Domains));
    }
}

bool Instance_service_group::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("domains"))))
    {
        std::vector<std::shared_ptr<Instance_service_group_domains_inner>> refVal_setDomains;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("domains"))), refVal_setDomains );
        setDomains(refVal_setDomains);
    }
    return ok;
}

utility::string_t Instance_service_group::getName() const
{
    return m_Name;
}

void Instance_service_group::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Instance_service_group::nameIsSet() const
{
    return m_NameIsSet;
}

void Instance_service_group::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Instance_service_group::getUuid() const
{
    return m_Uuid;
}

void Instance_service_group::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool Instance_service_group::uuidIsSet() const
{
    return m_UuidIsSet;
}

void Instance_service_group::unsetUuid()
{
    m_UuidIsSet = false;
}
std::vector<std::shared_ptr<Instance_service_group_domains_inner>>& Instance_service_group::getDomains()
{
    return m_Domains;
}

void Instance_service_group::setDomains(const std::vector<std::shared_ptr<Instance_service_group_domains_inner>>& value)
{
    m_Domains = value;
    m_DomainsIsSet = true;
}

bool Instance_service_group::domainsIsSet() const
{
    return m_DomainsIsSet;
}

void Instance_service_group::unsetDomains()
{
    m_DomainsIsSet = false;
}
}
}
}
}


