/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Stop_instances_request_inner.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Stop_instances_request_inner::Stop_instances_request_inner()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Force = false;
    m_ForceIsSet = false;
    m_Drain_timeout_ms = 0;
    m_Drain_timeout_msIsSet = false;
}

Stop_instances_request_inner::~Stop_instances_request_inner()
{
}

void Stop_instances_request_inner::validate()
{
    // TODO: implement validation
}

web::json::value Stop_instances_request_inner::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_ForceIsSet)
    {
        val[utility::conversions::to_string_t(U("force"))] = ModelBase::toJson(m_Force);
    }
    if(m_Drain_timeout_msIsSet)
    {
        val[utility::conversions::to_string_t(U("drain_timeout_ms"))] = ModelBase::toJson(m_Drain_timeout_ms);
    }

    return val;
}

bool Stop_instances_request_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("force"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("force")));
        if(!fieldValue.is_null())
        {
            bool refVal_setForce;
            ok &= ModelBase::fromJson(fieldValue, refVal_setForce);
            setForce(refVal_setForce);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("drain_timeout_ms"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("drain_timeout_ms")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDrainTimeoutMs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDrainTimeoutMs);
            setDrainTimeoutMs(refVal_setDrainTimeoutMs);
        }
    }
    return ok;
}

void Stop_instances_request_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_ForceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("force")), m_Force));
    }
    if(m_Drain_timeout_msIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("drain_timeout_ms")), m_Drain_timeout_ms));
    }
}

bool Stop_instances_request_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("force"))))
    {
        bool refVal_setForce;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("force"))), refVal_setForce );
        setForce(refVal_setForce);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("drain_timeout_ms"))))
    {
        int32_t refVal_setDrainTimeoutMs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("drain_timeout_ms"))), refVal_setDrainTimeoutMs );
        setDrainTimeoutMs(refVal_setDrainTimeoutMs);
    }
    return ok;
}

utility::string_t Stop_instances_request_inner::getUuid() const
{
    return m_Uuid;
}

void Stop_instances_request_inner::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool Stop_instances_request_inner::uuidIsSet() const
{
    return m_UuidIsSet;
}

void Stop_instances_request_inner::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t Stop_instances_request_inner::getName() const
{
    return m_Name;
}

void Stop_instances_request_inner::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Stop_instances_request_inner::nameIsSet() const
{
    return m_NameIsSet;
}

void Stop_instances_request_inner::unsetName()
{
    m_NameIsSet = false;
}
bool Stop_instances_request_inner::isForce() const
{
    return m_Force;
}

void Stop_instances_request_inner::setForce(bool value)
{
    m_Force = value;
    m_ForceIsSet = true;
}

bool Stop_instances_request_inner::forceIsSet() const
{
    return m_ForceIsSet;
}

void Stop_instances_request_inner::unsetForce()
{
    m_ForceIsSet = false;
}
int32_t Stop_instances_request_inner::getDrainTimeoutMs() const
{
    return m_Drain_timeout_ms;
}

void Stop_instances_request_inner::setDrainTimeoutMs(int32_t value)
{
    m_Drain_timeout_ms = value;
    m_Drain_timeout_msIsSet = true;
}

bool Stop_instances_request_inner::drainTimeoutMsIsSet() const
{
    return m_Drain_timeout_msIsSet;
}

void Stop_instances_request_inner::unsetDrain_timeout_ms()
{
    m_Drain_timeout_msIsSet = false;
}
}
}
}
}


