/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Volume_mounted_by_inner.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Volume_mounted_by_inner::Volume_mounted_by_inner()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Readonly = false;
    m_ReadonlyIsSet = false;
}

Volume_mounted_by_inner::~Volume_mounted_by_inner()
{
}

void Volume_mounted_by_inner::validate()
{
    // TODO: implement validation
}

web::json::value Volume_mounted_by_inner::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_ReadonlyIsSet)
    {
        val[utility::conversions::to_string_t(U("readonly"))] = ModelBase::toJson(m_Readonly);
    }

    return val;
}

bool Volume_mounted_by_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("readonly"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("readonly")));
        if(!fieldValue.is_null())
        {
            bool refVal_setReadonly;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReadonly);
            setReadonly(refVal_setReadonly);
        }
    }
    return ok;
}

void Volume_mounted_by_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_ReadonlyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("readonly")), m_Readonly));
    }
}

bool Volume_mounted_by_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("readonly"))))
    {
        bool refVal_setReadonly;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("readonly"))), refVal_setReadonly );
        setReadonly(refVal_setReadonly);
    }
    return ok;
}

utility::string_t Volume_mounted_by_inner::getUuid() const
{
    return m_Uuid;
}

void Volume_mounted_by_inner::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool Volume_mounted_by_inner::uuidIsSet() const
{
    return m_UuidIsSet;
}

void Volume_mounted_by_inner::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t Volume_mounted_by_inner::getName() const
{
    return m_Name;
}

void Volume_mounted_by_inner::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Volume_mounted_by_inner::nameIsSet() const
{
    return m_NameIsSet;
}

void Volume_mounted_by_inner::unsetName()
{
    m_NameIsSet = false;
}
bool Volume_mounted_by_inner::isReadonly() const
{
    return m_Readonly;
}

void Volume_mounted_by_inner::setReadonly(bool value)
{
    m_Readonly = value;
    m_ReadonlyIsSet = true;
}

bool Volume_mounted_by_inner::readonlyIsSet() const
{
    return m_ReadonlyIsSet;
}

void Volume_mounted_by_inner::unsetReadonly()
{
    m_ReadonlyIsSet = false;
}
}
}
}
}


