/**
 * Unikraft Cloud Platform
 * This is the API of the Unikraft Cloud Platform. 
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: info@unikraft.cloud
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UnikraftCloudV1APIClient/model/Wait_for_instances_200_response_data.h"

namespace cloud {
namespace unikraft {
namespace v1 {
namespace model {



Wait_for_instances_200_response_data::Wait_for_instances_200_response_data()
{
    m_InstancesIsSet = false;
}

Wait_for_instances_200_response_data::~Wait_for_instances_200_response_data()
{
}

void Wait_for_instances_200_response_data::validate()
{
    // TODO: implement validation
}

web::json::value Wait_for_instances_200_response_data::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_InstancesIsSet)
    {
        val[utility::conversions::to_string_t(U("instances"))] = ModelBase::toJson(m_Instances);
    }

    return val;
}

bool Wait_for_instances_200_response_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("instances"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("instances")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Wait_for_instances_200_response_data_instances_inner>> refVal_setInstances;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInstances);
            setInstances(refVal_setInstances);
        }
    }
    return ok;
}

void Wait_for_instances_200_response_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_InstancesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("instances")), m_Instances));
    }
}

bool Wait_for_instances_200_response_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("instances"))))
    {
        std::vector<std::shared_ptr<Wait_for_instances_200_response_data_instances_inner>> refVal_setInstances;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("instances"))), refVal_setInstances );
        setInstances(refVal_setInstances);
    }
    return ok;
}

std::vector<std::shared_ptr<Wait_for_instances_200_response_data_instances_inner>>& Wait_for_instances_200_response_data::getInstances()
{
    return m_Instances;
}

void Wait_for_instances_200_response_data::setInstances(const std::vector<std::shared_ptr<Wait_for_instances_200_response_data_instances_inner>>& value)
{
    m_Instances = value;
    m_InstancesIsSet = true;
}

bool Wait_for_instances_200_response_data::instancesIsSet() const
{
    return m_InstancesIsSet;
}

void Wait_for_instances_200_response_data::unsetInstances()
{
    m_InstancesIsSet = false;
}
}
}
}
}


